stages:
  - test

test:
  image: $IMAGE
  stage: test
  before_script:
    - mix do local.hex --force, local.rebar --force, deps.get --force
  script:
    - mix test --cover
  parallel:
    matrix:
      - IMAGE: elixir:1.17-alpine
      - IMAGE: elixir:1.16-alpine
      - IMAGE: elixir:1.15-alpine
      - IMAGE: elixir:1.14-alpine
